### ISSUE TITLE
First channel number or chanel number range per mapping group

### ISSUE THREAD

**Issue by stevehop** [xteve-project/xTeVe#112]
**Is your feature request related to a problem? Please describe.**
After mapping and grouping channels from an IPTV provider's playlist, if the playlist changes temporarily i.e. a channel disappears from the playlist and later re-appears, the channel is potentially allocated a channel number a long way from the other channels of a group which when using Plex's TV guide makes it very hard to navigate the channels. 

**Describe the solution you'd like**
The ability to set a channel number starting point or range on a per Group Title basis:

Group Tile ¦ First Channel Number
01 - News ¦ 1000
02 - Sports ¦ 1100
03 - Movies ¦ 1200

**Comment by xteve-project** [comment]
The real problem is that the channels are disappearing from the M3U. If that happens, the channel is removed from the mapping. If the channel is available again, it will be a new channel for xTeVe. Every new channel gets the first free channel number from 1000. The value can be changed in the settings.json.

Allocating by group title will not work, what would happen if there are 120 news channels as described in your example?
The next problem is plex, if a channel gets a new number, it has to be reactivated in the plex mapping.

xTeVe cannot solve all problems, everyone wants a different mapping because everyone has different preferences.
The mapping was created because Plex has none and it should be as flexible as possible.
