### ISSUE TITLE
User-Agent Stuck on VLC/3.0.1

### ISSUE THREAD

**Issue by MCTyler** [xteve-project/xTeVe#113]
Buffer on, Buffer off.... 2.1.2 (121) Beta is stuck on User-Agent VLC/3.0.1 Showing in Log file.

![image](https://user-images.githubusercontent.com/6390898/78390487-4a520200-75aa-11ea-91b9-d9cc291a7628.png)

![image](https://user-images.githubusercontent.com/6390898/78390303-f21b0000-75a9-11ea-97f8-dfc0aaa358e2.png)

![image](https://user-images.githubusercontent.com/6390898/78390342-019a4900-75aa-11ea-9bd4-96f1487ca9b3.png)

Alexpaton tried it with Buffer on...........

**Comment by xteve-project** [comment]
Since we already had the topic yesterday, here is the answer from Discord:

Client User Agent from the log means: This is the client that is currently connecting to xTeVe (Emby, Plex or IPTV player). Since you have deactivated the buffer, your client receives a message and the provider URL that it should connect directly to the provider.

If xTeVe connects to the provider, the user agent from the xTeVe settings is used. For the provider,  xTeVe is the client.

**Comment by MCTyler** [comment]
Thanks for your patience and sorry for my bad memory....
