### ISSUE TITLE
NO Buffer does not work with plex/emby if there are too many redirects from the IPTV provider

### ISSUE THREAD

**Issue by brycelarge** [xteve-project/xTeVe#153]
Some IPTV providers do 2-3 redirects to the server that's supplying the feed and ffprobe does not seem to cope well with that many redirects so plex and emby fail to play the feed.

A simple fix would be to resolve the final destination, perhaps using curl "curl -Ls -o /dev/null -w %{url_effective} [URL]} then pass that url on.

**Comment by mar-mei** [comment]
With No Buffer, the streaming URL from the M3U is sent to Plex / Emby, xTeVe is then no longer involved. Plex / Emby connects directly to the provider.

**Comment by brycelarge** [comment]
Yes thats correct, but the URL is passed but that URL could be redirect 2-3 times in which case plex or emby fail to play the stream.

**Comment by mar-mei** [comment]
I hear this for the first time that Plex has problems with redirects. How did you find out that it's because of the redirects?
Since xTeVe has no video framework and therefore does not know what format (h264, h265, mpeg) or transport protocol (HTTP, RTSP, RTP, UDP) it is, the URL is sent to the client (Plex / Emby / M3U Player) with deactivated buffer.

**Comment by brycelarge** [comment]
xTeVe adds an additional redirect onto the stream, ffprobe which Plex / Emby use to probe the stream seems to be getting packet corrupt errors and thus Plex / Emby cannot get any information about the stream.

ffprobe throws out a packet error when there are 3 or more redirects on the xteve URL http://xteve:34400/stream/38b84b027f09aa81bc246fe18ae7d3e2

This ffprobe error comes out in the Plex / Emby logs:
11:44:24.986 [mpegts @ 0x474300] Could not detect TS packet size, defaulting to non-FEC/DVHS

When I test the xteve url with my local ffprobe I also get a similar error:
[mpegts @ 0x7faa5000ac00] Packet corrupt (stream = 0, dts = 1885357800).

When I look for the actual URL that xTeVe sent to Plex / Emby from the xTeVe log and use ffprobe again then I don't get any errors.

So all I'm asking is instead of sending the URL that's listed in the m3u rather resolve the final URL by using the curl script I gave above and send that URL to Plex / Emby instead.

**Comment by brycelarge** [comment]
To be honest, perhaps it not even the redirects causing this, maybe there is something else causing ffprobe to get those errors.

**Comment by brycelarge** [comment]
This is the error emby gives when xTeVe passes the URL to Emby

Playback Error
No compatible streams are currently available. Please try again later or contact your system administrator for details.

**Comment by brycelarge** [comment]
When I add my IPTV m3u link directly into Emby then streams play

**Comment by mar-mei** [comment]
The curl idea cannot be implemented that there is not only HTTP stream. My DVB-T TV tuner uses RTSP streams, so no HTTP.
The streams must always point to xTeVe so that the buffer settings can be changed without all clients having to reload the M3U / DVT lineup. The correct URL is then redirected to Plex / Emby.
If it doesn't work for you without the buffer, you should activate this. Plex and Emby are not compatible with all streams. If you have set up xTeVe in Emby as an HDHR tuner, you should switch it to M3U. Emby M3U is compatible with more formats.

**Comment by brycelarge** [comment]
Ok, was worth a try. Thanks for taking the time to converse with me.
