### ISSUE TITLE
Add options xteve

### ISSUE THREAD

**Issue by jeromim** [xteve-project/xTeVe#158]
they could add the timeshift option to xteve, an option that is sorely missed.
supports download xml.gz add epg, i have download files xml.gz and it gives error.

 thank you.

**Comment by MCTyler** [comment]
xTeVe use system clock to determine time....your other issue...I don't understand....Downloaded EPG? from where?

**Comment by jeromim** [comment]
there are EPGs that we buy that come with UTC different from my timezone, with the option you can correct the timeshift, this option exists in several iptv player programs.

**Comment by MCTyler** [comment]
Not really sure Marmei would re-code xTeVe to accommodate shortfalls in paid EPG, but it's his choice...GL.

**Comment by mar-mei** [comment]
If the time is right on all of your systems, the clients will correct the time difference. Assuming the time is right in the XMLTV file.
Here's an example:
```XML
<programme channel="123" start="20200714190000 +0000" stop="20200714214500 +0000">
  <title lang="en-GB">Live: Premier League Football</title>
  <sub-title lang="en-GB">Chelsea v Norwich City</sub-title>
  <new></new>
  <live></live>
</programme>
```
```
start="YYYY-MM-DD-HH:MM:SS +TIMESHIFT"
```
The game starts 07-14-2020 at 7pm in the UK (UTC). I live in UTC +2, for me the game starts at 9pm

Plex:
![grafik](https://user-images.githubusercontent.com/43099631/87336571-54d54d80-c542-11ea-96ab-c8909f42eed2.png)
Morgen = Tomorrow 

In order to fix any errors in the XMLTV file, it makes no sense to implement a timeshift in xTeVe.
- Errors should be corrected where they arise.
- If the EPG provider corrects the error, the correct time zone would have to be entered again in xTeVe.

Gzip is supported by xTeVe, maybe only your file is broken.
