### ISSUE TITLE
Channel Limit Configuration - Emby/Jellyfin

### ISSUE THREAD

**Issue by acollierr17** [xteve-project/xTeVe#249]
**Is your feature request related to a problem? Please describe.**
According to [the source code](https://github.com/xteve-project/xTeVe/blob/0e999b85b9c77c3fdcfcfaf5e96150523fd4481b/src/config.go#L49-L50), both the Plex Channel Limit and Unfiltered Channel limit are set to **480 channels**. However, Jellyfin/Emby doesn't seem to have that [limit](https://emby.media/community/index.php?/topic/72268-live-tv-channel-limit-channel-filtering-and-guide-grid-empty-sometimes/&do=findComment&comment=726942) (We use Jellyfin).

**Describe the solution you'd like**
A way to modify the channel limit so we're not restricted to the constraints of the predefined Plex limit.

**Describe alternatives you've considered**
- Modify the source code upping the limit and then compile a new build

**Additional context**
N/A

**Comment by MCTyler** [comment]
Ask Plex not xTeVe. Also, it's not a hardcoded limit, it's just all Plex can handle without crashing.

**Comment by acollierr17** [comment]
> Ask Plex not xTeVe. Also, it's not a hardcoded limit, it's just all Plex can handle without crashing.

Hey, I think you missed the most important part of the issue. We use Jellyfin, not Plex. Hence I'm asking if the channel limit can be configurable so we can up the channel limit. A channel limit we don't *have* to have.

**Comment by winguru** [comment]
So yes, the Unfiltered Channel Limit currently does limit the number of channels within xTeVe.  It just so happens to be set to the same limit as the Plex channel limit,

xTeVe currently is coded to allocate a fixed number of channels during the initialization of its structures.  I've not tried increasing that number or moving that to a configurable setting.  Removing any limit would involve more coding since the channel allocation routines would have to be modified.

Is there a specific channel limit you would like, or are you asking in general?   Note: I am not a code author on this project, nor do I have any particular input into any code decisions here.  I do have a fork that I've make a few changes on, if this is of particular and immediate concern, or you can recompile this code yourself with a higher limit.

**Comment by winguru** [comment]
Upon closer inspection of the xTeVe channel allocation code, the Channel Limit is not a hardcoded limit.  It is the initial allocation size, but channels are added using append(), which will increase the size of an array if needed.

I tested with Emby and an artificially low Channel Limit (48) set in xTeVe that I exceeded and encountered no issues.  So in actuality, there should be no issues exceeding 480 channels with xTeVe and using that with Emby/Jellyfin.

**Comment by acollierr17** [comment]
My apologies as I was talking to my friend and failed to mention this part. We are aware that this value is not hardcoded. And that it can be configured. But what happens with us is once the limit is exceeded, our streams are set to zero, which is the issue for us. Again, my bad for not mentioning that in the original issue.

**Comment by winguru** [comment]
@acollierr17 Can you clarify what you mean when you say, "our streams are set to zero"?  Do you mean that you don't see any channels listed in your "Mapping" screen?  Or that the M3U file xTeVe generates is empty?  Or that when you try to play a channel in Jellyfin that is says no streams are available when there should be?

Also, one more question:  Did you configure Jellyfin to use xTeVe as an HD Homerun or M3U source?  (I've used Emby, not Jellyfin, so I'm not as familiar with that product, so apologies if I reference Emby from time to time)

**Comment by MCTyler** [comment]
There is no Channel Limit for Emby/JellyFin, That warning is Generic. Please close, this is not a issue.
