### ISSUE TITLE
client has terminated

### ISSUE THREAD

**Issue by sheryus** [xteve-project/xTeVe#28]
i run on linux with plex i have always this error:
![image](https://user-images.githubusercontent.com/20800089/64862202-322c8c80-d632-11e9-8f31-399fc634af8d.png)

the stream work on vlc

**Comment by sheryus** [comment]
i test another m3u and now : 
![image](https://user-images.githubusercontent.com/20800089/64864062-89346080-d636-11e9-89fa-87fd935e238d.png)
i test on vlc its work . In setting Live tv on plex my tuner is red but when i config it i found it

**Comment by sheryus** [comment]
i see one picture on channel and stop directly

**Comment by mar-mei** [comment]
Presumably your provider blocks xTeVe. change the user agent in the xTeVe settings to VLC.
If xTeVe is installed on a server at a hoster, it may be that your provider has blocked the IP address.

**Comment by sheryus** [comment]
mpeg stream work but with HLS / m3u8 its always forbidden

**Comment by mar-mei** [comment]
Forbidden: Is an HTTP status, all connections to the server are HTTP connections, if the status is not OK, the connection is closed and status is in the log. So far, I was able to reproduce any HTTP error / status in VLC as well.

If the provider has a stream limit, there are usually problems with M3U8 when switching channels quickly, since the provider only notices a few seconds later that the old connection has ended.
