### ISSUE TITLE
Server sends an incompatible content type - EC: 4003 and on PMS "Error: could not tune channel" 

### ISSUE THREAD

**Issue by hyndraslic** [xteve-project/xTeVe#44]
Hey, 

I am trying to setup with plex but the I keep getting this error. I have buffer on as well. I can play the xteve.m3u just fine with VLC but can't on plex. I attached a screenshot 
![Capture](https://user-images.githubusercontent.com/34486426/67629023-2560a280-f846-11e9-9b4f-2168526fb558.PNG)

**Comment by mar-mei** [comment]
xTeVe expects a video stream, but your provider declares the data as HTML Document. That's why the streaming ended.

**Comment by foizashik** [comment]
Is there any fix for this? or it's something my provider needs to do?

**Comment by mar-mei** [comment]
In the xTeVe settings you can change the buffer to FFmpeg or VLC. Disadvantage: It takes longer for the stream to start.

**Comment by foizashik** [comment]
oh taking longer shouldn't be an issue as long as it works. So I tried doing that but I could never get the path to work on windows 10. Can you please show me an example on what it should look like on an windows? 

Thank you.

**Comment by foizashik** [comment]
nvm figured that out but now on plex it keeps loading for like a few mins and then says "this tv session has ended" and on terminal It says "buffering from ffmpeg" or vlc. Not sure if this is plex's problem or I'm doing something wrong

**Comment by mar-mei** [comment]
Plex is not compatible with all streaming formats. To test you can open the xteve.m3u in VLC.

**Comment by GroupMaster** [comment]
I would suggest not to use the xteve buffer if using it with plex. "this tv session has ended" in my experience often was the result of the epg data, maybe more specifically the channel IDs not being 100% correct. Try the IPTV-EPG website to prepair the channels, THEN send it to xteve. Be sure there are ZERO duplicate channels in IPTV-EPG (they appear red) before loading it into xteve.

My setup guide:
This is a method to using IPTV-EPG, xteve and plex together for a flawless guide.

Import the IPTV provider's m3u file and mark all of them as "No EPG, Exclude from m3u". Create new groups to suit your needs. Eg, local, entertainment, news, sports, latin. Set these new groups to "Get EPG". Go through each IPTV provided group and for each desired channel, set the TVG-ID to the correct one. Set the "Move to Group" drop-down to the new group you made of which it should belong and set the action to "Get EPG". Repeat for each channel. Save each page when complete!!

When all the wanted channels are moved to the custom groups, there should be 2 types of groups, The original "No EPG, exclude from m3u" and the ones you made set to "Get EPG". The reason for this is so when the IPTV provider makes changes to their line-up, it doesn't mess up your active line-up. This also assists on adding them to xteve. Don't change the channel numbers in IPTV-EPG for they are all unique and is not used by plex anyway! This will be done in plex at the end. You may re-order the items in each user created group which will determine the final guide order!

Verify the channels. Use the IPTV-EPG m3u URL and load it into VLC as a network stream. Use the FF button to skip through each channel. If any channels fail, remove it from your custom group. I made a "Dead" group just for these streams. 

The xteve part:
Now that a clean m3u has been made, go ahead and import the m3u and xml files into xteve from IPTV-EPG. Create a new "M3U: Group Title" filter for each custom group made that contains the final IPTV channels and set the exclude part to " ,a,e,i,u,o" (the first character is a space). After a filter for each group has been made, there should be ZERO channels listed under mapping. I personally started each label with a letter, A-Regionals,B-Entertainment,C-news..etc, in the order I want them to appear in the final guide to make things a little easier. After all filters are made, starting with the groups you want first, work your way down the list, change the exclude part of the filter to blank and put the " ,a,e,i,o,u" in the include section. The reason for this is to make sure each group gets added to the end of the list opposed to being mixed up, which often happens. Repeating the filter process can also correct changes made later. Just move the include string " ,a,e,i,o,u" to the exclude box for all groups to clear the mapped list and put them back in the correct order to restore everything. Some channels may require re-editing to fix broken channel icons and TVG-ID associations.

Each time any changes are made in IPTV-EPG to the line-up, channels added/removed or a TVG-ID updated, xteve needs to be deleted from plex and added back to rebuild the guide.

I have put a "few" hours of work into making this procedure and have tested it fairly well. I have none of the common issues including plex tuning to the wrong channel. Please note, if a TVG-ID does not exist or an incorrect one was selected, the guide may be incorrect or the channel will not be listed in plex. For PPV, 24/7 or any channel that will not have an associated TVG-ID, a static xml file can be made to provide basic epg data to allow the channel to be listed. This custom EPG is loaded directly into xteve and associated with the stream under mapping.

Sample static EPG xml file:
`<?xml version="1.0" encoding="UTF-8"?>`
`<!DOCTYPE tv SYSTEM "xmltv.dtd">`
`<tv date="10/20/2019" source-info-url="http://myserver.tv" source-info-name="CustomEPG">`
`  <channel id="24-7.13_reasons_why">`
`    <display-name>TV Binge - 13 Reasons Why</display-name>`
`  </channel>`
`  <programme start="20190101100000 +0000" stop="20201229123000 +0000" channel="24-7.13_reasons_why">`
`    <title lang="en">TV Binge - 13 Reasons Why</title>`
`    <desc lang="en">Follows teenager Clay Jensen, in his quest to uncover the story behind his classmate and crush, Hannah, and her decision to end her life.</desc>`
`    <category lang="en">Entertainment</category>`
`	<category lang="en">Series</category>`
`	<icon src="https://m.media-amazon.com/images/M/MV5BMTA2OTQxNzQtMDQ5OC00NDczLWFhYjEtN2UyMmIwNGZlZDM4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY1000_CR0,0,675,1000_AL_.jpg"/>`
`    <video>`
`      <colour>yes</colour>`
`      <quality>HDTV</quality>`
`    </video>`
`    <previously-shown/>`
`    <rating>`
`      <value>TV-MA</value>`
`    </rating>`
`  </programme>`
`</tv>`

Note: Only 1 <programme> is needed for each channel because `<programme start="20190101100000 +0000" stop="20201229123000 +0000"` defines the show as 2 years long. This date range will need to be updated before the 2 years are up or else the guide will be empty for the channel after 12/29/2020 in this example. I am unsure what happens if a very long duration is specified...

Enjoy
