### ISSUE TITLE
Add setting to automatically assign default XMLTV file and channel

### ISSUE THREAD

**Issue by adelatour11** [xteve-project/xTeVe#45]
I use xTeVe to consolidate a lot of different m3u files and XTeVe is the best tool i found to help me manage my files !

As you may already know if a stream source is new and no XML file or channel is assigned, the channel is not active. The m3u files I use are updated every 6 hours so I spend a lot of time to update the XMLTV file channel manually. 

I am looking for a way to save time, here are my ideas :

- add a General Setting option "Automatically assign default XMLTV file and Channel", when ticked this option enable that "xTeVe Dummy" xml file and "120 minutes" or other channels are assigned to each new channel when added

- An alternative solution would be to enable the assignment of XMLVTV file and channel using the API, the best way would be to update all channels at once.

**Comment by mar-mei** [comment]
The idea of xTeVe is to connect different M3U files with different XMLTV sources in order to have good EPG data.
If the IDs of the M3U and XMLTV file match, the channels are automatically mapped and activated.
It does not make any sense to automatically assign the dummy to all channels that do not have EPG data, so I can use any other IPTV app as well.

I suspect the updates of your provider will change the channel names in the playlist, so xTeVe loses the assignment. If your provider uses unique IDs for the streams, they can change the playlist without losing the assignment.

![image](https://user-images.githubusercontent.com/43099631/67711925-439fdd00-f9c3-11e9-98a2-ac43ab172652.png)

**Comment by adelatour11** [comment]
Thanks for your quick feedback, i get your point
to explain why it makes sense for me : i'm not really interested in EPG data for each channel (i have > 500 channels, my provider provides channels with different names each time :( so it's too much manual updates. That is why i'm more interested getting channels activated by default using dummy epg

**Comment by adelatour11** [comment]
Finally I have found a workaround to make sure all new channels are updated automatically using dummy epg

**Comment by jk7gr** [comment]
> Finally I have found a workaround (bash script) to make sure all new channels are updated automatically using dummy epg

Hi, I am interested to do the same think. Can you elaborate a little bit on your workaround?
Thank you!

**Comment by frasderp** [comment]
> Finally I have found a workaround (bash script) to make sure all new channels are updated automatically using dummy epg

Hey, trying to achieve the same thing... just stumbled across this page. Hoping you can share!

**Comment by MCTyler** [comment]
There is a Pyhton Script on xTeVe Discord for doing this....Just ask.

**Comment by aanze** [comment]
Hi there, just stumbling upon this post, as I'm looking for this exact feature aka being able to automatically assign dummy to new channels. Couldn't find any discord nor script, if anyone cares to share the knowledge ? :)

**Comment by asilvino** [comment]
@adelatour11 can you share the solution?
