### ISSUE TITLE
Channels DVR compatibility

### ISSUE THREAD

**Issue by annihilatethee** [xteve-project/xTeVe#77]
**Is your feature request related to a problem? Please describe.**
Flag needed for channels DVR functionality now that custom XMLs are allowed.

**Describe the solution you'd like**
Add the flag suggested in the “read-first” section of the Discord to allow Channels DVR functionality now that custom XMLs are allowed.

**Describe alternatives you've considered**
As far as I know this is the only way for it to work properly with Xteve. I’ve tried other proxys but Xteve is the best and most functional.

**Comment by MCTyler** [comment]
This is from Read-First on Discord concerning that App.....
"Why does xTeVe not work with the Channels app?

Unfortunately, Channels App does not support XMLTV files, the EPG data comes directly from SiliconDust.

The URL for the streams is expected in a specific format:
/auto/v422


Since v422 is the channel number and thus easy to guess, xTeVe always uses a different technique to generate the URLs for security reasons.

I could put a switch in xTeVe to convert the URL's into the desired format, but without EPG data in the Channels app, that does not make any sense to me at the moment."

**Comment by mar-mei** [comment]
@annihilatethee

**Comment by mar-mei** [comment]
Do you mean Channels DVR (paid version) or the Channels app (free)?

As far as I know, Channels DVR works when the buffer is activated. My info is also about 6 months old.

In the Discord was about the Channels app. I cannot test Channel DVR because this version has a subscription model and I will not pay money to test xTeVe in the future. I will only implement functions that I can test without paying money.

**Comment by annihilatethee** [comment]
It's the paid app which I understand the reasoning of you not being able to test. I have tried with the buffer and without but cannot get it to stream. The channels show up but it never actually streams, I believe it looks for the channel number the same way as the free app but I cannot be certain. I was hopeful that with the new functionality in the Channels DVR to allow the XML that it could be done but I understand you not wanting to implement something you cannot test yourself. I just really like xTeVe and it works much better than alternatives.

**Comment by go2tom42** [comment]
> 
> # This is from Read-First on Discord concerning that App.....
> 
> "Why does xTeVe not work with the Channels app?
> 
> Unfortunately, Channels App does not support XMLTV files, the EPG data comes directly from SiliconDust.
> 

Channels DVR supplies a XMLTV file

http://URL:8089/devices/ANY/guide/xmltv?duration=1209600
